### ISSUE TITLE
Rcon panel

### ISSUE THREAD

**Issue by Z1Meme** [QuentinGruber/h1z1-server#1185]
Should probably be made it's own repo but right now we don't have any way of directly interacting with the server while it's online except through the client. There should be some way of giving people admin or just managing the server overall from the console. Basically need to write a small program that can accept commands and send them via a custom udp protocol to the running h1emu server, as well as display server console entries.

**Comment by QuentinGruber** [comment]
Yep should be made in his own repo but since it requires modifications here it's still nice to have this issue on this repo.

**Comment by QuentinGruber** [comment]
Right now how things are handled we will need to built up a full protocol + his handler. Since h1emu protocol is thought and made for servers that communicate between them

**Comment by QuentinGruber** [comment]
> Right now how things are handled we will need to built up a full protocol + his handler. Since h1emu protocol is thought and made for servers that communicate between them

using https://github.com/websockets/ws could be cool so the rcon panel could be web based and some stuff could have a UI like /alert or /ban

**Comment by QuentinGruber** [comment]
created https://github.com/H1emu/rcon-manager/blob/main/README.md so it's kinda out of this repository now, i've the base stuff working on and won't be hard to pipe stdout to that rcon app. Since i've made it using websockets it could be a web based app like just a web client who query that and receive data from that wss. Will work on that soon.
