### ISSUE TITLE
External asset packs work for a small period when the user loads in

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1725]
**Describe the bug**
External asset packs still loads entities upon being logged on to a server. A user called Robbi on discord found this bug when he returned to the game and saw he could still "play," for a small amount of time with assets on. Although nothing will work and he gets weapon locked and eventually kicked, there's a small window of time when you first load in to a server that someone can potentially take advantage of using, for example, an asset pack that allows for seeing-through deck foundations essentially giving them ESP. 

I fortunately don't own an asset pack that lets me see-through foundations, but I provided a small clip showing this potential exploit while using Kronic's villa packs.

**To Reproduce**
Use any external asset pack and load onto a server and observe.

**Expected behavior**
Not 100% how asset validation works in its entirety, but from what I understand: a user loads up H1Z1, it begins to scan the users asset directories 1 by 1 until a CRC32 hash doesn't correctly match up with the provided CRC32 hash values. After this happens, the process of removing the player begins. 

**Screenshots**
https://streamable.com/4mhyea

**Comment by jamieduke** [comment]
Unfortunately that's by design to prevent gameplay issues and make asset scanning smooth for people. 
You're absolutely right about how it works, My original plan was to gather data for how long the hash calculation process takes, and tweak the kick timing based on that, but the former just didn't really happen. 

I think a great alternative as you said is to just not load entities until the player completes the scan process. Not quite sure how it'll work right now, but I'm definitely going to look into it for the next anticheat update. 

Thank you for your detailed issue, @Nikolassparrow.
