### ISSUE TITLE
"Trading" bullets upon death

### ISSUE THREAD

**Issue by Nikolassparrow** [QuentinGruber/h1z1-server#1976]
**Describe the bug**
Not necessarily a bug, but something to be added to provide a big QOL to PvP. 

**To Reproduce**
I think this is based upon ping but get 2 users and have them shoot each other at the same time in the head and observe that there's no "trading" of bullets upon death.

**Expected behavior**
If you shoot your gun, and you die while your bullets are traveling in the air, the bullets should still register damage on the target.

**Screenshots**
https://streamable.com/bpqgqa

In this clip, you can see the user hit the enemy and blood splatter off the guys face, but he didn't die or take damage.

**Comment by QuentinGruber** [comment]
This would be great but this currently happen because of how we identify the weapon that shoot the bullet, we take the one in the hand of the shooter and when a character die his gun is unloaded so the replication never happen. We have a way to just directly get the weapon but it open the door to malicious stuff + it would need a bunch of change in FairPlay stuff
